AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - spec/**/*
    - test/**/*

Layout/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
