images:
  - name: overseer/dotnet:2.2
    packages:
      - dotnet
    doc_links:
      - hub.docker.com
    tags:
      - c#
      - dotnet
      - microsoft
    info: Dotnet is beautiful and ugly at the same time.
  # - name: overseer/dotnet-splashkit:1.0
  #   packages:
  #     - dotnet
  #     - splashkit
  #   doc_links:
  #     - hub.docker.com
  #     - splashkit.io
  #   tags:
  #     - c#
  #     - dotnet
  #     - splashkit
  #     - microsoft
  #   info: Dotnet is more beautiful with splashkit, yet ugly at the same time.
